# Generated by Django 3.1.6 on 2021-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100, unique=True)),
                ('caticonname', models.CharField(max_length=1000)),
            ],
        ),
    ]
