# Generated by Django 3.1.6 on 2021-05-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scatid', models.AutoField(primary_key=True, serialize=False)),
                ('catnm', models.CharField(max_length=100)),
                ('Subcatnm', models.CharField(max_length=1000, unique=True)),
                ('subcaticonname', models.CharField(max_length=1000)),
            ],
        ),
    ]
