# Generated by Django 3.1.6 on 2021-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidding',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('uid', models.CharField(max_length=100)),
                ('bidamount', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
            ],
        ),
    ]
